### ISSUE TITLE
Wrong repo url on Xenial

### ISSUE THREAD

**Issue by mariussturm** [lesmyrmidons/ansible-role-mongodb#15]
On Ubuntu Xenial the repository url is set to `deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen` which is not correct. I could only overwrite the url with a `-e` command line switch but not from an external play. I think the url should not be set here: https://github.com/lesmyrmidons/ansible-role-mongodb/blob/06e3abc1a4390d01f2e402e80d9ae36948de42d2/vars/Ubuntu.yml#L5 but in the `/defaults`.

**Comment by lesmyrmidons** [comment]
Hi @mariussturm,

This variable is already exists in the defaults file `Ubuntu.yml` .
You just like to add the variable into playbook after the declaration of the role, for example:
```yml
roles:
    - role: lesmyrmidons.mongodb
      mongodb_repository: "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen"
```
